#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\manage\Views\User\Index.cshtml"
    using HST.Art.Core;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\manage\Views\User\Index.cshtml"
    using HST.Art.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/manage/Views/User/Index.cshtml")]
    public partial class _Areas_manage_Views_User_Index_cshtml : System.Web.Mvc.WebViewPage<User>
    {
        public _Areas_manage_Views_User_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

WriteLiteral("<!--[if lt IE 9]>\r\n<script type=\"text/javascript\" src=\"lib/html5shiv.js\"></script" +
">\r\n<script type=\"text/javascript\" src=\"lib/respond.min.js\"></script>\r\n<![endif]-" +
"->\r\n");

            
            #line 10 "..\..\Areas\manage\Views\User\Index.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Areas\manage\Views\User\Index.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--[if IE 6]>\r\n<script type=\"text/javascript\" src=\"lib/DD_belatedPNG_0.0.8a-mi" +
"n.js\" ></script>\r\n<script>DD_belatedPNG.fix(\'*\');</script>\r\n<![endif]-->\r\n\r\n<nav" +
"");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe67f;</i> 首页 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span> 个人信息 <a");

WriteLiteral(" class=\"btn btn-primary radius r\"");

WriteLiteral(" style=\"line-height:1.6em;margin-top:3px\"");

WriteLiteral(" href=\"javascript:location.replace(location.href);\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe68f;</i></a></nav>\r\n<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"tab-system\"");

WriteLiteral(" class=\"HuiTab\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"tabBar cl\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"current\"");

WriteLiteral(">个人信息</span>\r\n                <span");

WriteLiteral(" class=\"\"");

WriteLiteral(">修改密码</span>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"tabCon user-wrap\"");

WriteLiteral(" style=\"display: block;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"form-label col-xs-2 col-md-1\"");

WriteLiteral(">\r\n                        用户名：\r\n                    </label>\r\n                  " +
"  <div");

WriteLiteral(" class=\"formControls text col-xs-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                       ");

            
            #line 31 "..\..\Areas\manage\Views\User\Index.cshtml"
                  Write(Model.UserName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"form-label col-xs-2 col-md-1\"");

WriteLiteral(">\r\n                        手机：\r\n                    </label>\r\n                   " +
" <div");

WriteLiteral(" class=\"formControls text col-xs-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 39 "..\..\Areas\manage\Views\User\Index.cshtml"
                   Write(Model.Telephone);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"form-label col-xs-2 col-md-1\"");

WriteLiteral(">\r\n                        邮箱：\r\n                    </label>\r\n                   " +
" <div");

WriteLiteral(" class=\"formControls text col-xs-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 47 "..\..\Areas\manage\Views\User\Index.cshtml"
                   Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"form-label col-xs-2 col-md-1\"");

WriteLiteral(">\r\n                        创建时间：\r\n                    </label>\r\n                 " +
"   <div");

WriteLiteral(" class=\"formControls text col-xs-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 55 "..\..\Areas\manage\Views\User\Index.cshtml"
                   Write(Model.CreateDate.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"tabCon user-wrap\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                <form");

WriteLiteral(" id=\"form-admin\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"form-label col-xs-2 col-md-1\"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>原密码：</label>\r\n                        <div");

WriteLiteral(" class=\"formControls col-xs-8 col-md-3\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"input-text\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" placeholder=\"原密码\"");

WriteLiteral(" id=\"oldPwd\"");

WriteLiteral(" name=\"oldPwd\"");

WriteLiteral(">\r\n                        </div>\r\n                    </div>\r\n                  " +
"  <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"form-label col-xs-2 col-md-1\"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>新密码：</label>\r\n                        <div");

WriteLiteral(" class=\"formControls col-xs-8 col-md-3\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"input-text\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" placeholder=\"新密码\"");

WriteLiteral(" id=\"newPwd\"");

WriteLiteral(" name=\"newPwd\"");

WriteLiteral(">\r\n                        </div>\r\n                    </div>\r\n                  " +
"  <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"form-label col-xs-2 col-md-1\"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>确认新密码：</label>\r\n                        <div");

WriteLiteral(" class=\"formControls col-xs-8 col-md-3\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"input-text\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" placeholder=\"确认新密码\"");

WriteLiteral(" id=\"renewPwd\"");

WriteLiteral(" name=\"renewPwd\"");

WriteLiteral(">\r\n                        </div>\r\n                    </div>\r\n                  " +
"  <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-8 col-md-3 col-xs-offset-4 col-sm-offset-1\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" class=\"btn btn-primary radius\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral("></i> 修改</button>                      \r\n                        </div>\r\n        " +
"            </div>\r\n                </form>\r\n            </div>\r\n        </div>\r" +
"\n     \r\n    </div>\r\n</div>\r\n");

            
            #line 90 "..\..\Areas\manage\Views\User\Index.cshtml"
Write(Scripts.Render("~/bundles/validate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(function () {
            $(""#tab-system"").Huitab({
                index: 0
            });

            $(""#form-admin"").validate({
                rules: {
                    oldPwd: {
                        required: true,
                        minlength: 6
                    },
                    newPwd: {
                        required: true,
                        minlength: 6
                    },
                    renewPwd: {
                        required: true,
                        minlength: 6,
                        equalTo: ""#newPwd""
                    }
                },
                messages:{
                    oldPwd: {
                        required: ""请输入原密码"",
                    },
                    newPwd: {
                        required: ""请输入新密码"",
                    },
                    renewPwd: {
                        required: ""请输入确认新密码"",
                        equalTo: ""确认新密码与新密码不一致""
                    }
                },
                onkeyup: false,
                focusCleanup: true,
                success: ""valid"",
                submitHandler: function (form) {
                    $(form).ajaxSubmit({
                        type: 'post',
                        url: """);

            
            #line 132 "..\..\Areas\manage\Views\User\Index.cshtml"
                         Write(Url.Action("update"));

            
            #line default
            #line hidden
WriteLiteral(@""",
                        success: function (data) {
                            if (data == ""ok"") {
                                layer.alert('修改成功，请重新登录！', {
                                    icon: 6,
                                    closeBtn: 0,
                                    yes: function () {
                                        layer.closeAll();
                                        parent.location.reload();                                   
                                    }
                                });
                            } else if (data == ""error"") {
                                layer.alert('修改失败！', { icon: 5 });
                            } else {
                                layer.alert(data, { icon: 7 });
                            }
                        },
                        error: function (XmlHttpRequest, textStatus, errorThrown) {
                            layer.alert('修改失败！', { icon: 5 });
                        }
                    });
                }
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
