#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HST.Art.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Layout.cshtml"
  
    string action = Request.RequestContext.RouteData.GetRequiredString("Action");
    string queryName = string.IsNullOrEmpty(Request.QueryString["qtype"])?"": Request.QueryString["qtype"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"renderer\"");

WriteLiteral(" content=\"webkit|ie-comp|ie-stand\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0," +
"user-scalable=no\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Cache-Control\"");

WriteLiteral(" content=\"no-siteapp\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteLiteral(" content=\"\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 15 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteLiteral(" rel=\"Shortcut Icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(" />\r\n    <!--[if lt IE 9]>\r\n    <script type=\"text/javascript\" src=\"/Content/lib/" +
"html5shiv.js\"></script>\r\n    <script type=\"text/javascript\" src=\"/Content/lib/re" +
"spond.min.js\"></script>\r\n    <![endif]-->\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/webclient"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 22 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\_Layout.cshtml"
     if (action.Equals("index", StringComparison.InvariantCultureIgnoreCase))
    {
        
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
   Write(Styles.Render("~/swiper"));

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
                                  
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/webclient"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body ");

            
            #line 30 "..\..\Views\Shared\_Layout.cshtml"
  Write(action.Equals("index", StringComparison.InvariantCultureIgnoreCase)?"style=background:#f2f2f2":"");

            
            #line default
            #line hidden
WriteLiteral(">\r\n    <header>\r\n        <div");

WriteLiteral(" class=\"top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"cont top_div\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"fl logo\"");

WriteLiteral("><img");

WriteLiteral(" src=\"/Content/image/logo.jpg\"");

WriteLiteral(" /></p>\r\n                <div");

WriteLiteral(" class=\"fr top_fr\"");

WriteLiteral(">\r\n                    <p><i");

WriteLiteral(" class=\"iconfont icon-dianhua\"");

WriteLiteral("></i>010-6855086</p>\r\n                    <p><i");

WriteLiteral(" class=\"iconfont icon-email-icon\"");

WriteLiteral("></i>123456789@qq.com</p>\r\n                </div>\r\n            </div>\r\n        </" +
"div><!--/top-->\r\n    </header>\r\n    <nav>\r\n        <div");

WriteLiteral(" class=\"nav-logo\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1830), Tuple.Create("\"", 1865)
            
            #line 44 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1837), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 1837), false)
);

WriteLiteral("><img");

WriteLiteral(" src=\"/Content/image/logo.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral("></a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"nav-menu\"");

WriteLiteral(">\r\n            <span></span>\r\n            <span></span>\r\n            <span></span" +
">\r\n        </div>\r\n\r\n        <ul");

WriteLiteral(" class=\"nav-list\"");

WriteLiteral(">\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2111), Tuple.Create("\"", 2146)
            
            #line 53 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2118), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 2118), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 2147), Tuple.Create("\"", 2236)
            
            #line 53 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2155), Tuple.Create<System.Object, System.Int32>(action.Equals("index",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2155), false)
);

WriteLiteral(" >首页</a></li>\r\n            <li>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2288), Tuple.Create("\"", 2322)
            
            #line 55 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2295), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home")
            
            #line default
            #line hidden
, 2295), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 2323), Tuple.Create("\"", 2412)
            
            #line 55 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2331), Tuple.Create<System.Object, System.Int32>(action.Equals("about",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2331), false)
);

WriteLiteral(">协会概况</a>\r\n                <ul");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2482), Tuple.Create("\"", 2577)
            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2490), Tuple.Create<System.Object, System.Int32>(queryName.Equals("Synopsis",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2490), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2581), Tuple.Create("\"", 2648)
            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 2588), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home", new { QType = QSType.Synopsis })
            
            #line default
            #line hidden
, 2588), false)
);

WriteLiteral(">协会简介</a></li>\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2688), Tuple.Create("\"", 2780)
            
            #line 58 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2696), Tuple.Create<System.Object, System.Int32>(queryName.Equals("Frame",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2696), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2784), Tuple.Create("\"", 2848)
            
            #line 58 "..\..\Views\Shared\_Layout.cshtml"
                                              , Tuple.Create(Tuple.Create("", 2791), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home", new { QType = QSType.Frame })
            
            #line default
            #line hidden
, 2791), false)
);

WriteLiteral(">组织架构</a></li>\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2888), Tuple.Create("\"", 3051)
            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2896), Tuple.Create<System.Object, System.Int32>(queryName.Equals("List",StringComparison.InvariantCultureIgnoreCase)||queryName.Equals("Detail",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2896), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3055), Tuple.Create("\"", 3118)
            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                     , Tuple.Create(Tuple.Create("", 3062), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home", new { QType = QSType.List })
            
            #line default
            #line hidden
, 3062), false)
);

WriteLiteral(">协会会员</a></li>\r\n                </ul>\r\n            </li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">行业资讯</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">协会活动</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">社会公益</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">考级中心</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">下载专区</a></li>\r\n        </ul>\r\n    </nav>\r\n    <div");

WriteLiteral(" class=\"content-wrap\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 70 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"foot\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"foot_cont\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"foot_fl fl\"");

WriteLiteral(">\r\n                <p><span><img");

WriteLiteral(" src=\"images/ewm.jpg\"");

WriteLiteral(" /></span>扫码关注我们</p>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"foot_conts fl\"");

WriteLiteral(">\r\n                <b>联系我们</b>\r\n                <p>山东省艺术教育专业教育委员会</p>\r\n          " +
"      <p>地址：北京市丰台区昌宁大厦5层506</p>\r\n                <p>电话：010-6855068</p>\r\n        " +
"        <p>邮箱：123456789@163.com</p>\r\n            </div>\r\n            <p");

WriteLiteral(" class=\"fr index_ab\"");

WriteLiteral("><a><i></i> 关于我们</a></p>\r\n\r\n        </div>\r\n    </div>\r\n    <footer>京ICP备13003730" +
"号-1</footer>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(document).ready(function () {
            var topMain = $(""header"").height() + 15
            var nav = $(""nav"");
            $(window).scroll(function () {
                if ($(window).scrollTop() > topMain) {
                    nav.addClass(""nav_scroll"");

                } else {
                    nav.removeClass(""nav_scroll"");
                }
            });         
        })

        $(document).click(function () {
            $('.nav-list').removeClass('open')
        })
        $('.nav-menu,.nav-list').click(function (e) { e.stopPropagation() })
        $('nav').find('.nav-menu').click(function (e) {
            $('.nav-list').toggleClass('open')
        })
    </script>
");

WriteLiteral("    ");

            
            #line 112 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("Scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
