#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Shared\_Layout.cshtml"
    using HST.Art.Core;
    
    #line default
    #line hidden
    using HST.Art.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Layout.cshtml"
  
    string action = Request.RequestContext.RouteData.GetRequiredString("Action");
    string queryName = string.IsNullOrEmpty(Request.QueryString["qtype"]) ? "" : Request.QueryString["qtype"];

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"renderer\"");

WriteLiteral(" content=\"webkit|ie-comp|ie-stand\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0," +
"user-scalable=no\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Cache-Control\"");

WriteLiteral(" content=\"no-siteapp\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteLiteral(" content=\"\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 17 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteLiteral(" rel=\"Shortcut Icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(" />\r\n    <!--[if lt IE 9]>\r\n    <script type=\"text/javascript\" src=\"/Content/lib/" +
"html5shiv.js\"></script>\r\n    <script type=\"text/javascript\" src=\"/Content/lib/re" +
"spond.min.js\"></script>\r\n    <![endif]-->\r\n");

WriteLiteral("    ");

            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/webclient"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
     if (action.Equals("index", StringComparison.InvariantCultureIgnoreCase))
    {
        
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\_Layout.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1170), Tuple.Create("\"", 1205)
, Tuple.Create(Tuple.Create("", 1177), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/swiper.min.css")
, 1177), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1239), Tuple.Create("\"", 1280)
, Tuple.Create(Tuple.Create("", 1246), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/owl.carousel.min.css")
, 1246), false)
);

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("   \r\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/webclient"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body ");

            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
  Write(action.Equals("index", StringComparison.InvariantCultureIgnoreCase) ? "style=background:#f2f2f2" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n    <header>\r\n        <div");

WriteLiteral(" class=\"top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"cont top_div\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("Header", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div><!--/top-->\r\n    </header>\r\n    <nav>\r\n      " +
"  <div");

WriteLiteral(" class=\"nav-logo\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1754), Tuple.Create("\"", 1789)
            
            #line 44 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1761), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 1761), false)
);

WriteLiteral("><img");

WriteLiteral(" src=\"/Content/image/logo.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral("></a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"nav-menu\"");

WriteLiteral(">\r\n            <span></span>\r\n            <span></span>\r\n            <span></span" +
">\r\n        </div>\r\n\r\n        <ul");

WriteLiteral(" class=\"nav-list\"");

WriteLiteral(">\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2035), Tuple.Create("\"", 2070)
            
            #line 53 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2042), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 2042), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 2071), Tuple.Create("\"", 2224)
            
            #line 53 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2079), Tuple.Create<System.Object, System.Int32>(action.Equals("index",StringComparison.InvariantCultureIgnoreCase)||action.Equals("certificate",StringComparison.InvariantCulture)?"active":""
            
            #line default
            #line hidden
, 2079), false)
);

WriteLiteral(">首页</a></li>\r\n            <li>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2275), Tuple.Create("\"", 2309)
            
            #line 55 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2282), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home")
            
            #line default
            #line hidden
, 2282), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 2310), Tuple.Create("\"", 2399)
            
            #line 55 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2318), Tuple.Create<System.Object, System.Int32>(action.Equals("about",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2318), false)
);

WriteLiteral(">协会概况</a>\r\n                <ul");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2469), Tuple.Create("\"", 2564)
            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2477), Tuple.Create<System.Object, System.Int32>(queryName.Equals("Synopsis",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2477), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2568), Tuple.Create("\"", 2635)
            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 2575), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home", new { qtype = QSType.synopsis })
            
            #line default
            #line hidden
, 2575), false)
);

WriteLiteral(">协会简介</a></li>\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2675), Tuple.Create("\"", 2767)
            
            #line 58 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2683), Tuple.Create<System.Object, System.Int32>(queryName.Equals("Frame",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2683), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2771), Tuple.Create("\"", 2835)
            
            #line 58 "..\..\Views\Shared\_Layout.cshtml"
                                              , Tuple.Create(Tuple.Create("", 2778), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home", new { qtype = QSType.frame })
            
            #line default
            #line hidden
, 2778), false)
);

WriteLiteral(">组织架构</a></li>\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2875), Tuple.Create("\"", 3108)
            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2883), Tuple.Create<System.Object, System.Int32>(action.Equals("about",StringComparison.InvariantCultureIgnoreCase)&&(queryName.Equals("List",StringComparison.InvariantCultureIgnoreCase)||queryName.Equals("Detail",StringComparison.InvariantCultureIgnoreCase))?"active":""
            
            #line default
            #line hidden
, 2883), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3112), Tuple.Create("\"", 3175)
            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                           , Tuple.Create(Tuple.Create("", 3119), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home", new { qtype = QSType.list })
            
            #line default
            #line hidden
, 3119), false)
);

WriteLiteral(">协会会员</a></li>\r\n                </ul>\r\n            </li>\r\n            <li>\r\n     " +
"           <a");

WriteAttribute("class", Tuple.Create(" class=\"", 3270), Tuple.Create("\"", 3362)
            
            #line 63 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3278), Tuple.Create<System.Object, System.Int32>(action.Equals("industry",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 3278), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 3363), Tuple.Create("\"", 3393)
            
            #line 63 "..\..\Views\Shared\_Layout.cshtml"
                                      , Tuple.Create(Tuple.Create("", 3370), Tuple.Create<System.Object, System.Int32>(Url.Action("industry")
            
            #line default
            #line hidden
, 3370), false)
);

WriteLiteral(">行业资讯</a>\r\n");

WriteLiteral("                ");

            
            #line 64 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Industry }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 3557), Tuple.Create("\"", 3652)
            
            #line 67 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3565), Tuple.Create<System.Object, System.Int32>(action.Equals("association",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 3565), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 3653), Tuple.Create("\"", 3686)
            
            #line 67 "..\..\Views\Shared\_Layout.cshtml"
                                         , Tuple.Create(Tuple.Create("", 3660), Tuple.Create<System.Object, System.Int32>(Url.Action("association")
            
            #line default
            #line hidden
, 3660), false)
);

WriteLiteral(">协会活动</a>\r\n");

WriteLiteral("                ");

            
            #line 68 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Association }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 3853), Tuple.Create("\"", 3943)
            
            #line 71 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3861), Tuple.Create<System.Object, System.Int32>(action.Equals("social",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 3861), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 3944), Tuple.Create("\"", 3972)
            
            #line 71 "..\..\Views\Shared\_Layout.cshtml"
                                    , Tuple.Create(Tuple.Create("", 3951), Tuple.Create<System.Object, System.Int32>(Url.Action("social")
            
            #line default
            #line hidden
, 3951), false)
);

WriteLiteral(">社会公益</a>\r\n");

WriteLiteral("                ");

            
            #line 72 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Social }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 4134), Tuple.Create("\"", 4229)
            
            #line 75 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4142), Tuple.Create<System.Object, System.Int32>(action.Equals("examination",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 4142), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 4230), Tuple.Create("\"", 4263)
            
            #line 75 "..\..\Views\Shared\_Layout.cshtml"
                                         , Tuple.Create(Tuple.Create("", 4237), Tuple.Create<System.Object, System.Int32>(Url.Action("examination")
            
            #line default
            #line hidden
, 4237), false)
);

WriteLiteral(">考级中心</a>\r\n");

WriteLiteral("                ");

            
            #line 76 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Examination }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 4430), Tuple.Create("\"", 4522)
            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4438), Tuple.Create<System.Object, System.Int32>(action.Equals("download",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 4438), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 4523), Tuple.Create("\"", 4553)
            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"
                                      , Tuple.Create(Tuple.Create("", 4530), Tuple.Create<System.Object, System.Int32>(Url.Action("download")
            
            #line default
            #line hidden
, 4530), false)
);

WriteLiteral(">下载专区</a>\r\n");

WriteLiteral("                ");

            
            #line 80 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Download }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n        </ul>\r\n    </nav>\r\n    <div");

WriteLiteral(" class=\"content-wrap\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 85 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"foot\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"foot_cont\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 89 "..\..\Views\Shared\_Layout.cshtml"
       Write(Html.Action("Footer", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <footer>京ICP备13003730号-1</footer>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(document).ready(function () {
            var topMain = $(""header"").height() + 15
            var nav = $(""nav"");
            $(window).scroll(function () {
                if ($(window).scrollTop() > topMain) {
                    nav.addClass(""nav_scroll"");

                } else {
                    nav.removeClass(""nav_scroll"");
                }
            });
        })

        $(document).click(function () {
            $('.nav-list').removeClass('open')
        })
        $('.nav-menu,.nav-list').click(function (e) { e.stopPropagation() })
        $('nav').find('.nav-menu').click(function (e) {
            $('.nav-list').toggleClass('open')
        })
    </script>
");

WriteLiteral("    ");

            
            #line 115 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("Scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
