#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cncbk_resource;
    
    #line 4 "..\..\Views\ResAdmin\Add.cshtml"
    using cncbk_resource.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ResAdmin/Add.cshtml")]
    public partial class _Views_ResAdmin_Add_cshtml : System.Web.Mvc.WebViewPage<ResAdminViewModel>
    {
        public _Views_ResAdmin_Add_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\ResAdmin\Add.cshtml"
  
    Layout = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\ResAdmin\Add.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\ResAdmin\Add.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\ResAdmin\Add.cshtml"
Write(Scripts.Render("~/bundles/validate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\ResAdmin\Add.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .form-horizontal .form-label {\r\n        text-align: right;\r\n    }\r\n</style" +
">\r\n<article");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Views\ResAdmin\Add.cshtml"
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\ResAdmin\Add.cshtml"
     using (Ajax.BeginForm("Add", "ResAdmin", new AjaxOptions() { HttpMethod = "Post", OnSuccess = "formSuccess(data)", OnBegin = "disSubmit('sub_btn')", OnComplete = "enSubmit('sub_btn')" }, new { id = "form-good-add", @class = "form form-horizontal" }))
    {
        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\ResAdmin\Add.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\ResAdmin\Add.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\ResAdmin\Add.cshtml"
   Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\ResAdmin\Add.cshtml"
                                  

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>用户名：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.TextBoxFor(m => m.UserName, new { placeholder = "请输入用户名", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.UserName, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>手机号：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.TextBoxFor(m => m.Phone, new { placeholder = "请输入手机号", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.Phone, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral(">邮箱：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.TextBoxFor(m => m.Email, new { placeholder = "请输入邮箱", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.Email, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>密码：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 45 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.PasswordFor(m => m.Password, new { placeholder = "请设置初始密码", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 46 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.Password, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>角色：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"select select-box\"");

WriteLiteral(" id=\"sel_role\"");

WriteLiteral(">\r\n");

            
            #line 54 "..\..\Views\ResAdmin\Add.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\ResAdmin\Add.cshtml"
                     if (Model.RoleList == null || Model.RoleList.Count <= 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">请选择角色</option>\r\n");

            
            #line 57 "..\..\Views\ResAdmin\Add.cshtml"
                    }
                    else
                    {
                        foreach (var item in Model.RoleList)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2895), Tuple.Create("\"", 2911)
            
            #line 62 "..\..\Views\ResAdmin\Add.cshtml"
, Tuple.Create(Tuple.Create("", 2903), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 2903), false)
);

WriteLiteral(">");

            
            #line 62 "..\..\Views\ResAdmin\Add.cshtml"
                                                Write(item.RoleName);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 63 "..\..\Views\ResAdmin\Add.cshtml"

                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </select>\r\n");

WriteLiteral("                ");

            
            #line 67 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.TextBoxFor(m => m.RoleId, new { @class = "input-text input-hid" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 68 "..\..\Views\ResAdmin\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.RoleId, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral(">状态：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"select select-box\"");

WriteLiteral(" name=\"State\"");

WriteLiteral(">\r\n                    <option");

WriteLiteral(" value=\"0\"");

WriteLiteral(">启用</option>\r\n                    <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">禁用</option>\r\n                </select>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(" class=\"col-xs-6  col-xs-offset-3 col-sm-offset-2 mt-10\"");

WriteLiteral(">\r\n\r\n                <button");

WriteLiteral(" class=\"btn btn-primary radius\"");

WriteLiteral(" id=\"sub_btn\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe632;</i> 保存并提交</button>\r\n                <input");

WriteLiteral(" name=\"\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"layer_close();\"");

WriteLiteral(" class=\"btn btn-default radius \"");

WriteLiteral(" value=\"&nbsp;取&nbsp;&nbsp;&nbsp;&nbsp;消&nbsp;\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n");

            
            #line 87 "..\..\Views\ResAdmin\Add.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</article>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        if ($(""#sel_role"").val().length>0) {
            $(""#RoleId"").val($(""#sel_role"").val()).blur();
        }
        $(""#sel_role"").change(function () {
            $(""#RoleId"").val($(this).val()).blur();
        })

    })
    function formSuccess(result) {
        if (result != null) {
            if (result.isSuccess) {
                var index = parent.layer.getFrameIndex(window.name);
                layer.alert('保存成功！', {
                    icon: 6,
                    closeBtn: 0,
                    yes: function () {
                        parent.table1.ajax.reload();
                        parent.layer.close(index);
                    }
                });
            } else
                layer.alert('保存失败！', { icon: 5 });//icon:6为开心图
        } else
            layer.alert('保存失败！', { icon: 5 });//icon:6为开心图
    }
</script>");

        }
    }
}
#pragma warning restore 1591
