#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\ResAdmin\Update.cshtml"
    using CNCBK_Res_Domain.Repositories;
    
    #line default
    #line hidden
    using cncbk_resource;
    
    #line 5 "..\..\Views\ResAdmin\Update.cshtml"
    using cncbk_resource.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ResAdmin/Update.cshtml")]
    public partial class _Views_ResAdmin_Update_cshtml : System.Web.Mvc.WebViewPage<ResAdminViewModel>
    {
        public _Views_ResAdmin_Update_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\ResAdmin\Update.cshtml"
  
    Layout = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 9 "..\..\Views\ResAdmin\Update.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\ResAdmin\Update.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\ResAdmin\Update.cshtml"
Write(Scripts.Render("~/bundles/validate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\ResAdmin\Update.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .form-horizontal .form-label {\r\n        text-align: right;\r\n    }\r\n</style" +
">\r\n<article");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\ResAdmin\Update.cshtml"
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\ResAdmin\Update.cshtml"
     using (Ajax.BeginForm("Update", "ResAdmin", new AjaxOptions() { HttpMethod = "Post", OnSuccess = "formSuccess(data)", OnBegin = "disSubmit('sub_btn')", OnComplete = "enSubmit('sub_btn')" }, new { id = "form-good-add", @class = "form form-horizontal" }))
    {
        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\ResAdmin\Update.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\ResAdmin\Update.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\ResAdmin\Update.cshtml"
   Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\ResAdmin\Update.cshtml"
                                  
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\ResAdmin\Update.cshtml"
   Write(Html.HiddenFor(m => m.Remark));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\ResAdmin\Update.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>用户名：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

            
            #line 27 "..\..\Views\ResAdmin\Update.cshtml"
                
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\ResAdmin\Update.cshtml"
                 if (Model.IsSupAdmin)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"input-text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1078), Tuple.Create("\"", 1101)
            
            #line 29 "..\..\Views\ResAdmin\Update.cshtml"
, Tuple.Create(Tuple.Create("", 1086), Tuple.Create<System.Object, System.Int32>(Model.UserName
            
            #line default
            #line hidden
, 1086), false)
);

WriteLiteral(" />\r\n");

            
            #line 30 "..\..\Views\ResAdmin\Update.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\ResAdmin\Update.cshtml"
               Write(Html.HiddenFor(m => m.UserName));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\ResAdmin\Update.cshtml"
                                                    
                }
                else
                {   
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\ResAdmin\Update.cshtml"
               Write(Html.TextBoxFor(m => m.UserName, new { placeholder = "请输入用户名", @class = "input-text" }));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\ResAdmin\Update.cshtml"
                                                                                                            
                    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\ResAdmin\Update.cshtml"
               Write(Html.ValidationMessageFor(m => m.UserName, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\ResAdmin\Update.cshtml"
                                                                                                     
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 38 "..\..\Views\ResAdmin\Update.cshtml"
            
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\ResAdmin\Update.cshtml"
             if (ViewBag.IsSupAdmin)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-default radius\"");

WriteLiteral(" style=\"height:auto;padding:6px 10px;font-size:12px\"");

WriteLiteral(" onclick=\"initPwd()\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">初始化密码</button>\r\n                </div>\r\n");

            
            #line 43 "..\..\Views\ResAdmin\Update.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>手机号：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Views\ResAdmin\Update.cshtml"
           Write(Html.TextBoxFor(m => m.Phone, new { placeholder = "请输入手机号", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 49 "..\..\Views\ResAdmin\Update.cshtml"
           Write(Html.ValidationMessageFor(m => m.Phone, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral(">邮箱：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Views\ResAdmin\Update.cshtml"
           Write(Html.TextBoxFor(m => m.Email, new { placeholder = "请输入邮箱", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Views\ResAdmin\Update.cshtml"
           Write(Html.ValidationMessageFor(m => m.Email, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>角色：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

            
            #line 62 "..\..\Views\ResAdmin\Update.cshtml"
                
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\ResAdmin\Update.cshtml"
                 if (Model.IsSupAdmin)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" class=\"input-text\"");

WriteLiteral(" disabled");

WriteLiteral(" value=\"超级管理员\"");

WriteLiteral(" />\r\n");

            
            #line 65 "..\..\Views\ResAdmin\Update.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <select");

WriteLiteral(" class=\"select select-box\"");

WriteLiteral(" id=\"sel_role\"");

WriteLiteral(">\r\n");

            
            #line 69 "..\..\Views\ResAdmin\Update.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\ResAdmin\Update.cshtml"
                         if (Model.RoleList == null || Model.RoleList.Count <= 0)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">请选择角色</option>\r\n");

            
            #line 72 "..\..\Views\ResAdmin\Update.cshtml"
                        }
                        else
                        {
                            foreach (var item in Model.RoleList)
                            {
                                if (Model.RoleId == item.Id.ToString())
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 3479), Tuple.Create("\"", 3495)
            
            #line 79 "..\..\Views\ResAdmin\Update.cshtml"
, Tuple.Create(Tuple.Create("", 3487), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 3487), false)
);

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">");

            
            #line 79 "..\..\Views\ResAdmin\Update.cshtml"
                                                                            Write(item.RoleName);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 80 "..\..\Views\ResAdmin\Update.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 3693), Tuple.Create("\"", 3709)
            
            #line 83 "..\..\Views\ResAdmin\Update.cshtml"
, Tuple.Create(Tuple.Create("", 3701), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 3701), false)
);

WriteLiteral(">");

            
            #line 83 "..\..\Views\ResAdmin\Update.cshtml"
                                                        Write(item.RoleName);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 84 "..\..\Views\ResAdmin\Update.cshtml"
                                }
                            }

                        }

            
            #line default
            #line hidden
WriteLiteral("                    </select>\r\n");

            
            #line 89 "..\..\Views\ResAdmin\Update.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 90 "..\..\Views\ResAdmin\Update.cshtml"
           Write(Html.TextBoxFor(m => m.RoleId, new { @class = "input-text input-hid" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 91 "..\..\Views\ResAdmin\Update.cshtml"
           Write(Html.ValidationMessageFor(m => m.RoleId, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral(">状态：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

            
            #line 97 "..\..\Views\ResAdmin\Update.cshtml"
                
            
            #line default
            #line hidden
            
            #line 97 "..\..\Views\ResAdmin\Update.cshtml"
                 if (Model.IsSupAdmin)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"input-text\"");

WriteLiteral(" value=\"启用\"");

WriteLiteral(" />\r\n");

            
            #line 100 "..\..\Views\ResAdmin\Update.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\ResAdmin\Update.cshtml"
               Write(Html.HiddenFor(m => m.State));

            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\ResAdmin\Update.cshtml"
                                                 
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <select");

WriteLiteral(" class=\"select select-box\"");

WriteLiteral(" name=\"State\"");

WriteLiteral(">\r\n");

            
            #line 105 "..\..\Views\ResAdmin\Update.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\ResAdmin\Update.cshtml"
                          
                            if (Model.State == 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <option");

WriteLiteral(" value=\"0\"");

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">启用</option>\r\n");

            
            #line 109 "..\..\Views\ResAdmin\Update.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <option");

WriteLiteral(" value=\"0\"");

WriteLiteral(">启用</option>\r\n");

            
            #line 113 "..\..\Views\ResAdmin\Update.cshtml"
                            }
                            if (Model.State == 1)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">不启用</option>\r\n");

            
            #line 117 "..\..\Views\ResAdmin\Update.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">不启用</option>\r\n");

            
            #line 121 "..\..\Views\ResAdmin\Update.cshtml"
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                    </select>\r\n");

            
            #line 124 "..\..\Views\ResAdmin\Update.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n        </div>\r\n");

            
            #line 129 "..\..\Views\ResAdmin\Update.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(" class=\"col-xs-6  col-xs-offset-3 col-sm-offset-2 mt-10\"");

WriteLiteral(">\r\n\r\n                <button");

WriteLiteral(" class=\"btn btn-primary radius\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"sub_btn\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe632;</i> 保存并提交</button>\r\n                <input");

WriteLiteral(" name=\"\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"layer_close();\"");

WriteLiteral(" class=\"btn btn-default radius \"");

WriteLiteral(" value=\"&nbsp;取&nbsp;&nbsp;&nbsp;&nbsp;消&nbsp;\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n");

            
            #line 137 "..\..\Views\ResAdmin\Update.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("</article>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        $(""#sel_role"").change(function () {
            $(""#RoleId"").val($(this).val()).blur();
        })

    })

    function initPwd() {
        layer.confirm('初始化密码为123456，您确定要初始化吗？', function (e) {
            $.ajax({
                url: """);

            
            #line 150 "..\..\Views\ResAdmin\Update.cshtml"
                 Write(Url.Action("InitPwd"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                type: \"post\",\r\n                data: { uid: ");

            
            #line 152 "..\..\Views\ResAdmin\Update.cshtml"
                        Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(@" },
                success: function (data) {
                    if (data == ""ok"") {
                        layer.alert('初始化成功！', { icon: 6 });
                    } else if (data == ""error"") {
                        layer.alert('操作失败！', { icon: 5 });
                    }
                    else {
                        layer.alert(data, { icon: 7 });
                    }
                },
                error: function (data) { layer.alert('操作失败！', { icon: 5 }); }
            })
        })
    }

    function formSuccess(result) {
        if (result != null) {
            if (result.isSuccess) {
                var index = parent.layer.getFrameIndex(window.name);
                layer.alert('保存成功！', {
                    icon: 6,
                    closeBtn: 0,
                    yes: function () {
                        parent.table1.ajax.reload();
                        parent.layer.close(index);
                    }
                });
            } else
                layer.alert('保存失败！', { icon: 5 });//icon:6为开心图
        } else
            layer.alert('保存失败！', { icon: 5 });//icon:6为开心图
    }

</script>");

        }
    }
}
#pragma warning restore 1591
