#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cncbk_resource;
    
    #line 5 "..\..\Views\ResPackge\Edit.cshtml"
    using cncbk_resource.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ResPackge/Edit.cshtml")]
    public partial class _Views_ResPackge_Edit_cshtml : System.Web.Mvc.WebViewPage<ResourcePackageViewModel>
    {
        public _Views_ResPackge_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\ResPackge\Edit.cshtml"
  
    Layout = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\ResPackge\Edit.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\ResPackge\Edit.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\ResPackge\Edit.cshtml"
Write(Scripts.Render("~/bundles/validate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\ResPackge\Edit.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .form-horizontal .form-label {\r\n        text-align: right;\r\n    }\r\n</style" +
">\r\n<article");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n");

            
            #line 18 "..\..\Views\ResPackge\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\ResPackge\Edit.cshtml"
     if (Model == null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n            <img");

WriteLiteral(" src=\"/Content/image/no-data.png\"");

WriteLiteral(" />\r\n            <p>暂无数据</p>\r\n        </div>\r\n");

            
            #line 24 "..\..\Views\ResPackge\Edit.cshtml"
    }
    else
    {
        using (Ajax.BeginForm("Edit", "ResPackge", new AjaxOptions() { HttpMethod = "Post", OnSuccess = "formSuccess(data)",OnBegin = "disSubmit('sub_btn')", OnComplete = "enSubmit('sub_btn')" }, new { id = "form-good-add", @class = "form form-horizontal" }))
        {
            
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\ResPackge\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\ResPackge\Edit.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\ResPackge\Edit.cshtml"
       Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\ResPackge\Edit.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>资料包名：</label>\r\n                <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Views\ResPackge\Edit.cshtml"
               Write(Html.TextBoxFor(m => m.Name, new { placeholder = "资料包名称", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Views\ResPackge\Edit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Name, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>排序：</label>\r\n                <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"number\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1569), Tuple.Create("\"", 1588)
            
            #line 41 "..\..\Views\ResPackge\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1577), Tuple.Create<System.Object, System.Int32>(Model.Sort
            
            #line default
            #line hidden
, 1577), false)
);

WriteLiteral(" name=\"Sort\"");

WriteLiteral(" min=\"1\"");

WriteLiteral(" class=\"input-text\"");

WriteLiteral(" onchange=\"changecount(this,1,1)\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral(">状态：</label>\r\n                <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                    <select");

WriteLiteral(" class=\"select select-box\"");

WriteLiteral(" name=\"State\"");

WriteLiteral(">\r\n");

            
            #line 48 "..\..\Views\ResPackge\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\ResPackge\Edit.cshtml"
                         foreach (KeyValuePair<int, string> item in ViewBag.select as Dictionary<int, string>)
                    {

            
            #line default
            #line hidden
WriteLiteral("                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2121), Tuple.Create("\"", 2138)
            
            #line 50 "..\..\Views\ResPackge\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2129), Tuple.Create<System.Object, System.Int32>(item.Key
            
            #line default
            #line hidden
, 2129), false)
);

WriteLiteral(" ");

            
            #line 50 "..\..\Views\ResPackge\Edit.cshtml"
                                                  Write(Model.State == item.Key ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 50 "..\..\Views\ResPackge\Edit.cshtml"
                                                                                              Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 51 "..\..\Views\ResPackge\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </select>\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(" class=\"col-xs-6  col-xs-offset-3 col-sm-offset-2 mt-10\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-primary radius\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"sub_btn\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe632;</i> 保存并提交</button>\r\n                    <input");

WriteLiteral(" name=\"\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"layer_close();\"");

WriteLiteral(" class=\"btn btn-default radius \"");

WriteLiteral(" value=\"&nbsp;取&nbsp;&nbsp;&nbsp;&nbsp;消&nbsp;\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n");

            
            #line 61 "..\..\Views\ResPackge\Edit.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</article>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

    $(function () {
    });

    function formSuccess(result) {
        if (result == ""ok"") {
            var index = parent.layer.getFrameIndex(window.name);
            layer.alert('保存成功！', {
                icon: 6,
                closeBtn: 0,
                yes: function () {
                    parent.table1.ajax.reload();
                    parent.layer.close(index);
                }
            });
        } else {
            layer.alert('保存失败！', { icon: 5 });//icon:6为开心图
        }
    }
</script>");

        }
    }
}
#pragma warning restore 1591
