#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cncbk_resource;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ResPackge/List.cshtml")]
    public partial class _Views_ResPackge_List_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_ResPackge_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!--[if lt IE 9]>\r\n<script type=\"text/javascript\" src=\"lib/html5shiv.js\"></script" +
">\r\n<script type=\"text/javascript\" src=\"lib/respond.min.js\"></script>\r\n<![endif]-" +
"->\r\n");

            
            #line 5 "..\..\Views\ResPackge\List.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\ResPackge\List.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--[if IE 6]>\r\n<script type=\"text/javascript\" src=\"lib/DD_belatedPNG_0.0.8a-mi" +
"n.js\" ></script>\r\n<script>DD_belatedPNG.fix(\'*\');</script>\r\n<![endif]-->\r\n<nav");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe67f;</i> 首页 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span> 用户学习资料 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span> 资料包管理 <a");

WriteLiteral(" class=\"btn btn-success radius r\"");

WriteLiteral(" style=\"line-height:1.6em;margin-top:3px\"");

WriteLiteral(" href=\"javascript:location.replace(location.href);\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe68f;</i></a></nav>\r\n<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"cl pd-5 bg-1 bk-gray mt-10 search-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">资料包名：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"packgeName\"");

WriteLiteral(" placeholder=\"请输入资料包名\"");

WriteLiteral(" class=\"input-text lg inline\"");

WriteLiteral(" />\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">状态：</span>\r\n        <select");

WriteLiteral(" name=\"sel_orderstate\"");

WriteLiteral(" id=\"sel_packgeState\"");

WriteLiteral(" class=\"select select-box inline\"");

WriteLiteral(">\r\n            <option");

WriteLiteral(" value=\"-1\"");

WriteLiteral(">全部</option>\r\n            <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">启用</option>\r\n            <option");

WriteLiteral(" value=\"0\"");

WriteLiteral(">禁用</option>\r\n        </select>\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">更新时间：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onclick=\"WdatePicker()\"");

WriteLiteral(" placeholder=\"更新时间\"");

WriteLiteral(" id=\"upgradeTime\"");

WriteLiteral(" class=\"input-text inline Wdate\"");

WriteLiteral(" />\r\n        <button");

WriteLiteral(" name=\"search\"");

WriteLiteral(" id=\"search\"");

WriteLiteral(" class=\"btn btn-success ml-10\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe665;</i> 搜索</button>\r\n        <button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1589), Tuple.Create("\"", 1640)
, Tuple.Create(Tuple.Create("", 1599), Tuple.Create("resPage_add(\'添加资料包\',\'", 1599), true)
            
            #line 25 "..\..\Views\ResPackge\List.cshtml"
, Tuple.Create(Tuple.Create("", 1620), Tuple.Create<System.Object, System.Int32>(Url.Action("Add")
            
            #line default
            #line hidden
, 1620), false)
, Tuple.Create(Tuple.Create("", 1638), Tuple.Create("\')", 1638), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">添加资料包</button>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"mt-10\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"tbTable\"");

WriteLiteral(" class=\"table table-border table-bordered table-bg table-sort\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr");

WriteLiteral(" class=\"text-c\"");

WriteLiteral(">\r\n                    <th");

WriteLiteral(" width=\"8%\"");

WriteLiteral(">序号</th>\r\n                    <th");

WriteLiteral(" width=\"24%\"");

WriteLiteral(">资料包名称</th>\r\n                    <th");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">状态</th>\r\n                    <th");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">排序</th>\r\n                    <th");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">更新时间</th>\r\n                    <th");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">管理</th>\r\n                </tr>\r\n            </thead>\r\n        </table>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

            
            #line 43 "..\..\Views\ResPackge\List.cshtml"
Write(Scripts.Render("~/bundles/datatable"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var table1 = null;
        $(function () {
            table1 = initializeTable();
            $(""#search"").click(function () {
                table1.ajax.reload();
            });

            //输入名称回车查询
            $(""#packgeName"").keypress(function (e) {
                if (e.which == 13) {
                    table1.ajax.reload();
                    $(""#search"").focus();
                }
            });
        });

        /*资料包-编辑*/
        function resPage_edit(title, url, id) {
            var index = layer.open({
                type: 2,
                title: title,
                area: ['700px', '320px'],
                content: url + ""?id="" + id
            });
        }

        /*资料包-添加*/
        function resPage_add(title, url) {
            var index = layer.open({
                type: 2,
                title: title,
                area: ['700px', '320px'],
                content: url
            });
        }
        /*删除资料包*/
        function resPage_del(id) {
            layer.confirm('确认要删除该资料包吗？', function (e) {
                $.ajax({
                    url: """);

            
            #line 85 "..\..\Views\ResPackge\List.cshtml"
                     Write(Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteral(@""",
                    type: ""post"",
                    data: { id: id },
                    success: function (data) {
                        if (data == ""ok"") {
                            layer.alert('操作成功！', {
                                icon: 6,
                                closeBtn: 0,
                                yes: function () {
                                    table1.ajax.reload();
                                    layer.closeAll();
                                }
                            });
                        } else if (data == ""error"") {
                            layer.alert('操作失败！', { icon: 5 });
                        }
                        else {
                            layer.alert(data, { icon: 7 });
                        }
                    },
                    error: function (data) { layer.alert('操作失败！', { icon: 5 }); }
                })
            });
        }
        function initializeTable() {
            var dataTable = $('#tbTable').DataTable({
                ""serverSide"": true,
                ""ajax"": {
                    ""url"": """);

            
            #line 113 "..\..\Views\ResPackge\List.cshtml"
                       Write(Url.Action("GetJsonData"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    \"type\": \"post\",\r\n                    \"data\": function (da" +
"ta) {\r\n                        data.pageIndex = (data.start / data.length) + 1;\r" +
"\n                        data.name = $(\"#packgeName\").val();\r\n                  " +
"      data.state = $(\"#sel_packgeState\").val();\r\n                        data.up" +
"gradetime = $(\"#upgradeTime\").val();\r\n                    }\r\n                },\r" +
"\n                \"columns\": [\r\n                      { \"defaultContent\": \"\" },\r\n" +
"                      { \"mDataProp\": \"Name\" },\r\n                      { \"mDataPr" +
"op\": \"State\" },\r\n                      { \"mDataProp\": \"Sort\" },\r\n               " +
"       { \"mDataProp\": \"UpgradeTimeStr\" },\r\n                      { \"defaultConte" +
"nt\": \"\" }\r\n\r\n                ],\r\n                \"columnDefs\": [\r\n              " +
"   {\r\n                     \"targets\": [2],\r\n                     \"data\": \"State\"" +
",\r\n                     \"render\": function (data, type, full) {\r\n               " +
"          var result = data;\r\n                         if (data) {\r\n            " +
"                 result = \"<span class=\\\"label label-success radius\\\">启用</span>\"" +
";\r\n                         } else {\r\n                             result = \"<sp" +
"an class=\\\"label label-danger radius\\\">禁用</span>\";\r\n                         }\r\n" +
"\r\n                         return result;\r\n                     }\r\n             " +
"    },\r\n                {\r\n                    \"targets\": [-1],\r\n               " +
"     \"data\": \"Id\",\r\n                    \"render\": function (data, type, full) {\r" +
"\n                        var tmpString = \"<a style=\\\"text-decoration:none\\\" onCl" +
"ick=\\\"resPage_edit(\'修改资料包\',\'");

            
            #line 150 "..\..\Views\ResPackge\List.cshtml"
                                                                                                      Write(Url.Action("Edit"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" href=\\\"javascript:;\\\" title=\\\"编辑\\\">编辑</a>\";\r\n                  " +
"      tmpString += \"<a href=\\\"javascript:;\\\" onClick=\\\"resPage_del(\" + data + \")" +
"\\\"  title=\\\"删除\\\">删除</a>\";\r\n                        return tmpString;\r\n          " +
"          }\r\n                }\r\n                ],\r\n                \"fnDrawCallb" +
"ack\": function () {\r\n                    var api = this.api();\r\n                " +
"    var startIndex = api.context[0]._iDisplayStart;\r\n                    api.col" +
"umn(0).nodes().each(function (cell, i) {\r\n                        cell.innerHTML" +
" = startIndex + i + 1;\r\n                    });\r\n                },\r\n           " +
"     \"rowCallback\": function (row, data, displayIndex) {\r\n                    $(" +
"row).attr(\"class\", \"text-c\");\r\n                    $(row).children(\'td\').eq(2).a" +
"ttr(\"class\", \"td-status\");\r\n                    $(row).children(\'td\').eq(5).attr" +
"(\"class\", \"td-manage\");\r\n                },\r\n                \"initComplete\": fun" +
"ction (settings, json) {\r\n\r\n                },\r\n                language: {\r\n   " +
"                 lengthMenu: \'\',\r\n                    loadingRecords: \'数据加载中...\'" +
",\r\n                    paginate: {\r\n                        previous: \"上一页\",\r\n  " +
"                      next: \"下一页\",\r\n                        first: \"\",\r\n        " +
"                last: \"\"\r\n                    },\r\n                    zeroRecord" +
"s: \"暂无数据\",\r\n\r\n                    info: \"<span class=\'pagesStyle\'>总共<span class=" +
"\'recordsStyle\'> _TOTAL_ 条,计 _PAGES_ </span>页，当前显示 _START_ -- _END_ 条记录 </span>\"," +
"\r\n                    infoEmpty: \"0条记录\",\r\n                    infoFiltered: \"\"\r\n" +
"                },\r\n                \"searching\": false,\r\n                \"orderi" +
"ng\": false,\r\n                \"autoWidth\": false,\r\n                \"iDisplayLengt" +
"h\": 10,\r\n                \"processing\": true,\r\n                //destroy: true, /" +
"/Cannot reinitialise DataTable,解决重新加载表格内容问题\r\n\r\n            });\r\n            retu" +
"rn dataTable;\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
