#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cncbk_resource;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ResRole/List.cshtml")]
    public partial class _Views_ResRole_List_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_ResRole_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\ResRole\List.cshtml"
  
    ViewBag.Title = "角色权限";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!--[if lt IE 9]>\r\n<script type=\"text/javascript\" src=\"lib/html5shiv.js\"></sc" +
"ript>\r\n<script type=\"text/javascript\" src=\"lib/respond.min.js\"></script>\r\n<![end" +
"if]-->\r\n");

            
            #line 10 "..\..\Views\ResRole\List.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\ResRole\List.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--[if IE 6]>\r\n<script type=\"text/javascript\" src=\"lib/DD_belatedPNG_0.0.8a-mi" +
"n.js\" ></script>\r\n<script>DD_belatedPNG.fix(\'*\');</script>\r\n<![endif]-->\r\n<nav");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe67f;</i> 首页 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span> 系统管理 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span> 角色权限 <a");

WriteLiteral(" class=\"btn btn-success radius r\"");

WriteLiteral(" style=\"line-height:1.6em;margin-top:3px\"");

WriteLiteral(" href=\"javascript:location.replace(location.href);\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe68f;</i></a></nav>\r\n<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"cl pd-5 bg-1 bk-gray mt-10 search-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">角色名：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"userName\"");

WriteLiteral(" placeholder=\"请输入角色名关键字\"");

WriteLiteral(" class=\"input-text lg inline\"");

WriteLiteral(" />\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">创建时间：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onclick=\"WdatePicker()\"");

WriteLiteral(" placeholder=\"创建时间\"");

WriteLiteral(" id=\"sTime\"");

WriteLiteral(" class=\"input-text inline Wdate\"");

WriteLiteral(" />\r\n        <button");

WriteLiteral(" name=\"search\"");

WriteLiteral(" id=\"search\"");

WriteLiteral(" class=\"btn btn-success ml-10\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe665;</i> 搜索</button>\r\n        <button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1329), Tuple.Create("\"", 1379)
, Tuple.Create(Tuple.Create("", 1339), Tuple.Create("resRole_add(\'添加角色\',\'", 1339), true)
            
            #line 24 "..\..\Views\ResRole\List.cshtml"
, Tuple.Create(Tuple.Create("", 1359), Tuple.Create<System.Object, System.Int32>(Url.Action("Add")
            
            #line default
            #line hidden
, 1359), false)
, Tuple.Create(Tuple.Create("", 1377), Tuple.Create("\')", 1377), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">添加角色</button>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"mt-10\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"tbTable\"");

WriteLiteral(" class=\"table table-border table-bordered table-bg table-sort\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr");

WriteLiteral(" class=\"text-c\"");

WriteLiteral(">\r\n                    <th");

WriteLiteral(" width=\"8%\"");

WriteLiteral(">序号</th>\r\n                    <th");

WriteLiteral(" width=\"45%\"");

WriteLiteral(">角色名</th>\r\n                    <th");

WriteLiteral(" width=\"30%\"");

WriteLiteral(">创建时间</th>\r\n                    <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(">管理</th>\r\n                </tr>\r\n            </thead>\r\n        </table>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

            
            #line 40 "..\..\Views\ResRole\List.cshtml"
Write(Scripts.Render("~/bundles/datatable"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var table1 = null;\r\n        $(function () {\r\n            table1 = init" +
"ializeTable();\r\n            $(\"#search\").click(function () {\r\n                ta" +
"ble1.ajax.reload();\r\n            });\r\n\r\n\r\n            //输入名称回车查询\r\n            $(" +
"\"#userName\").keypress(function (e) {\r\n                if (e.which == 13) {\r\n    " +
"                table1.ajax.reload();\r\n                    $(\"#search\").focus();" +
"\r\n                }\r\n            });\r\n        });\r\n\r\n        /*更新*/\r\n        fun" +
"ction resRole_update(title, url, id) {\r\n            var index = layer.open({\r\n  " +
"              type: 2,\r\n                title: title,\r\n                area: [\'7" +
"00px\', \'400px\'],\r\n                content: url + \"?id=\" + id\r\n            });\r\n " +
"       }\r\n        /*添加*/\r\n        function resRole_add(title, url) {\r\n          " +
"  var index = layer.open({\r\n                type: 2,\r\n                title: tit" +
"le,\r\n                area: [\'700px\', \'400px\'],\r\n                content: url\r\n  " +
"          });\r\n        }\r\n\r\n        /*删除*/\r\n        function resRole_del(obj, id" +
") {\r\n            layer.confirm(\'确认要删除该管理员吗？\', function (index) {\r\n              " +
"  var thisobj = $(obj);\r\n                $.getJSON(\"/ResRole/delete/\" + id, func" +
"tion (data) {\r\n                    if (data.isSuccess) {\r\n                      " +
"  layer.alert(\'操作成功！\', {\r\n                            icon: 6,\r\n                " +
"            closeBtn: 0,\r\n                            yes: function () {\r\n      " +
"                          table1.ajax.reload();\r\n                               " +
" layer.closeAll();\r\n                            }\r\n                        });\r\n" +
"                    } else\r\n                        layer.alert(data.message, { " +
"icon: 5 });\r\n                })\r\n            });\r\n        }\r\n        function Ch" +
"angeDateFormat(val) {\r\n            if (val != null) {\r\n                var date " +
"= new Date(parseInt(val.replace(\"/Date(\", \"\").replace(\")/\", \"\"), 10));\r\n        " +
"        //月份为0-11，所以+1，月份小于10时补个0\r\n                var month = date.getMonth() +" +
" 1 < 10 ? \"0\" + (date.getMonth() + 1) : date.getMonth() + 1;\r\n                va" +
"r currentDate = date.getDate() < 10 ? \"0\" + date.getDate() : date.getDate();\r\n  " +
"              return date.getFullYear() + \"-\" + month + \"-\" + currentDate;\r\n    " +
"        }\r\n            return \"\";\r\n        }\r\n        function initializeTable()" +
" {\r\n            var dataTable = $(\'#tbTable\').DataTable({\r\n                \"serv" +
"erSide\": true,\r\n                \"ajax\": {\r\n                    \"url\": \"/ResRole/" +
"GetJsonData\",\r\n                    \"type\": \"post\",\r\n                    \"data\": " +
"function (data) {\r\n                        data.pageIndex = (data.start / data.l" +
"ength) + 1;\r\n                        data.name = $(\"#userName\").val();\r\n        " +
"                data.stime = $(\"#sTime\").val();\r\n                    }\r\n        " +
"        },\r\n                \"columns\": [\r\n                      { \"defaultConten" +
"t\": \"\" },\r\n                      { \"mDataProp\": \"RoleName\" },\r\n                 " +
"     { \"mDataProp\": \"RoleCtime\" },\r\n                      { \"defaultContent\": \"\"" +
" }\r\n\r\n                ],\r\n                \"columnDefs\": [\r\n                     " +
"    {\r\n                             \"targets\": [2],\r\n                           " +
"  \"data\": \"RoleCtime\",\r\n                             \"render\": function (data, t" +
"ype, full) {\r\n                                 return ChangeDateFormat(data)\r\n  " +
"                           }\r\n                         },\r\n                {\r\n  " +
"                  \"targets\": [-1],\r\n                    \"data\": \"Id\",\r\n         " +
"           \"render\": function (data, type, full) {\r\n                        if (" +
"full.RoleType<=0) {\r\n                            var tmpString = \"<a href=\\\"java" +
"script:;\\\" onClick=\\\"resRole_update(\'修改管理员\',\'");

            
            #line 140 "..\..\Views\ResRole\List.cshtml"
                                                                                                   Write(Url.Action("Update"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\"  title=\\\"修改\\\">修改</a>\";\r\n                            tmpString +" +
"= \"<a href=\\\"javascript:;\\\" onClick=\\\"resRole_del(this,\" + data + \")\\\"  title=\\\"" +
"删除\\\">删除</a>\";\r\n                            return tmpString;\r\n                  " +
"      } else {\r\n                            return \"不可操作\";\r\n                    " +
"    }\r\n                    }\r\n                }\r\n                ],\r\n           " +
"     \"fnDrawCallback\": function () {\r\n                    var api = this.api();\r" +
"\n                    var startIndex = api.context[0]._iDisplayStart;\r\n          " +
"          api.column(0).nodes().each(function (cell, i) {\r\n                     " +
"   cell.innerHTML = startIndex + i + 1;\r\n                    });\r\n              " +
"  },\r\n                \"rowCallback\": function (row, data, displayIndex) {\r\n     " +
"               $(row).attr(\"class\", \"text-c\");\r\n                    $(row).child" +
"ren(\'td\').eq(3).attr(\"class\", \"td-manage\");\r\n                },\r\n               " +
" \"initComplete\": function (settings, json) {\r\n\r\n                },\r\n            " +
"    language: {\r\n                    lengthMenu: \'\',\r\n                    loadin" +
"gRecords: \'数据加载中...\',\r\n                    paginate: {\r\n                        " +
"previous: \"上一页\",\r\n                        next: \"下一页\",\r\n                        " +
"first: \"\",\r\n                        last: \"\"\r\n                    },\r\n          " +
"          zeroRecords: \"暂无数据\",\r\n\r\n                    info: \"<span class=\'pagesS" +
"tyle\'>总共<span class=\'recordsStyle\'> _TOTAL_ 条,计 _PAGES_ </span>页，当前显示 _START_ --" +
" _END_ 条记录 </span>\",\r\n                    infoEmpty: \"0条记录\",\r\n                  " +
"  infoFiltered: \"\"\r\n                },\r\n                \"searching\": false,\r\n   " +
"             \"ordering\": false,\r\n                \"autoWidth\": false,\r\n          " +
"      \"iDisplayLength\": 10,\r\n                \"processing\": true,\r\n              " +
"  //destroy: true, //Cannot reinitialise DataTable,解决重新加载表格内容问题\r\n\r\n            }" +
");\r\n            return dataTable;\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
