#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cncbk_resource;
    
    #line 2 "..\..\Views\ResRole\Update.cshtml"
    using cncbk_resource.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ResRole/Update.cshtml")]
    public partial class _Views_ResRole_Update_cshtml : System.Web.Mvc.WebViewPage<ResRoleViewModel>
    {
        public _Views_ResRole_Update_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\ResRole\Update.cshtml"
  Layout = "";
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\ResRole\Update.cshtml"
Write(Styles.Render("~/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\ResRole\Update.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .form-horizontal .form-label {\r\n        text-align: right;\r\n    }\r\n</style" +
">\r\n<article");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Views\ResRole\Update.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\ResRole\Update.cshtml"
     using (Ajax.BeginForm("Update", "ResRole", new AjaxOptions() { HttpMethod = "Post", OnSuccess = "formSuccess(data)", OnBegin = "disSubmit('sub_btn')", OnComplete = "enSubmit('sub_btn')" }, new { id = "form-good-add", @class = "form form-horizontal" }))
    {
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\ResRole\Update.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\ResRole\Update.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"rolelist\"");

WriteLiteral(" name=\"rolelist\"");

WriteLiteral(" />\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>角色名称：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\ResRole\Update.cshtml"
           Write(Html.TextBoxFor(m => m.RoleName, new { placeholder = "角色名称", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\ResRole\Update.cshtml"
           Write(Html.ValidationMessageFor(m => m.RoleName, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>菜单权限：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"selectpicker form-control\"");

WriteLiteral(" id=\"sel_fir\"");

WriteLiteral("  multiple");

WriteLiteral(" title=\"请选择权限\"");

WriteLiteral(" data-hide-disabled=\"true\"");

WriteLiteral(" data-live-search=\"false\"");

WriteLiteral(" data-selected-text-format=\"count > 5\"");

WriteLiteral(">\r\n                   \r\n                </select>\r\n\r\n            </div>\r\n        " +
"</div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(" class=\"col-xs-6  col-xs-offset-3 col-sm-offset-2 mt-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 35 "..\..\Views\ResRole\Update.cshtml"
           Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <button");

WriteLiteral(" class=\"btn btn-primary radius\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"sub_btn\"");

WriteLiteral(" onclick=\"return subdata();\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe632;</i> 保存并提交</button>\r\n                <input");

WriteLiteral(" name=\"\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"layer_close();\"");

WriteLiteral(" class=\"btn btn-default radius \"");

WriteLiteral(" value=\"&nbsp;取&nbsp;&nbsp;&nbsp;&nbsp;消&nbsp;\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n");

            
            #line 40 "..\..\Views\ResRole\Update.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</article>\r\n");

            
            #line 42 "..\..\Views\ResRole\Update.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 43 "..\..\Views\ResRole\Update.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 44 "..\..\Views\ResRole\Update.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 45 "..\..\Views\ResRole\Update.cshtml"
Write(Scripts.Render("~/bundles/validate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n    $(function(){\r\n        $(\'.selectpicker\').selectpicker();\r\n    })\r\n    v" +
"ar jsonobj=");

            
            #line 51 "..\..\Views\ResRole\Update.cshtml"
           Write(Html.Raw(ViewBag.select));

            
            #line default
            #line hidden
WriteLiteral(";\r\n    var listint=\"");

            
            #line 52 "..\..\Views\ResRole\Update.cshtml"
            Write(string.Join(",",Model.menuList));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n    var idlist=[];\r\n    if(listint!=\'\')\r\n        idlist=listint.split(\',\');\r\n" +
"    $(\'.selectpicker\').html(gethtml(jsonobj,0));\r\n    function gethtml(obj,pid){" +
"\r\n        if(obj!=null){\r\n            var htmllist=[];\r\n            for (var i i" +
"n obj) {\r\n                if(obj[i].ParentId==pid)\r\n                {\r\n         " +
"           if(obj[i].ParentId==0){\r\n                        htmllist.push(\"<optg" +
"roup id=\'\"+obj[i].Id+\"\' label=\'\"+obj[i].Name+\"\'>\");\r\n                        htm" +
"llist.push(gethtml(obj,obj[i].Id));\r\n                        htmllist.push(\"</op" +
"tgroup>\");\r\n                    }\r\n                    else\r\n                   " +
" {\r\n                        htmllist.push(\" <option value=\'\"+obj[i].Id+\"\' \");\r\n " +
"                       htmllist.push(idlist.indexOf(\'\'+obj[i].Id+\'\')>-1?\"selecte" +
"d\":\"\");\r\n                        htmllist.push(\" >\"+obj[i].Name+\"</option>\");\r\n " +
"                   }    \r\n                }\r\n            }\r\n            return h" +
"tmllist.join(\'\');\r\n        }\r\n    }\r\n\r\n    function formSuccess(result) {\r\n     " +
"   if (result != null) {\r\n            if (result.isSuccess) {\r\n                v" +
"ar index = parent.layer.getFrameIndex(window.name);\r\n                layer.alert" +
"(\'保存成功！\', {\r\n                    icon: 6,\r\n                    closeBtn: 0,\r\n   " +
"                 yes: function () {\r\n                        parent.table1.ajax." +
"reload();\r\n                        parent.layer.close(index);\r\n                 " +
"   }\r\n                });\r\n            } else\r\n                layer.alert(\'保存失败" +
"！\', { icon: 5 });//icon:6为开心图\r\n        } else\r\n            layer.alert(\'保存失败！\', " +
"{ icon: 5 });//icon:6为开心图\r\n    }\r\n\r\n    function subdata(){\r\n        var thisval" +
"=$(\'.selectpicker\').selectpicker(\'val\');\r\n        if(thisval==null)\r\n           " +
" layer.msg(\"请选择权限\")\r\n        else{\r\n            $(\"#rolelist\").val(thisval);\r\n\r\n" +
"            return true;\r\n        }\r\n        return false;\r\n    }\r\n</script>");

        }
    }
}
#pragma warning restore 1591
